### ISSUE TITLE
sfdx sfpowerkit:project:manifest:diff does not list removed metadata components

### ISSUE THREAD

**Issue by reda-benhemmouche** [Accenture/sfpowerkit#261]
**Describe the bug**
When i run sfdx sfpowerkit:project:manifest:diff command it does not detect removed components

**To Reproduce**
_package1.xml content (SOURCE):_ 

```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>class1</members>
        <members>class2</members>
        <members>class3</members>
        <name>ApexClass</name>
    </types>
        <types>
        <members>MyWorkflow1</members>
        <members>MyWorkflow2</members>
        <name>Workflow</name>
    </types>
    <version>47.0</version>
</Package>
```

_package2.xml content(TARGET) :_ 
In this file, we remove **class1**,add **class4**, add **MyWorkflow3**

```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>class2</members>
        <members>class3</members>
        <members>class4</members>
        <name>ApexClass</name>
    </types>
        <types>
        <members>MyWorkflow1</members>
        <members>MyWorkflow2</members>
        <members>MyWorkflow3</members>
        <name>Workflow</name>
    </types>
    <version>47.0</version>
</Package>
```

_The result is :_ 
```
[
  {
    "status": "Added at Target",
    "type": "ApexClass",
    "member": "class4"
  },
  {
    "status": "Added at Target",
    "type": "Workflow",
    "member": "MyWorkflow3"
  }
]
```

**Expected behavior**
Expected result should reflect the changes between 2 compared manifest. We should get something like this : 
```
[
   {
    "status": "Removed from Target",
    "type": "ApexClass",
    "member": "class1"
  },
 {
    "status": "Added at Target",
    "type": "ApexClass",
    "member": "class4"
  },
  {
    "status": "Added at Target",
    "type": "Workflow",
    "member": "MyWorkflow3"
  }
]
```

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: MAC OS X 10.14.6
- Version of sfowerkit: 1.44.2
- Salesforce Org Version: N/A

**Additional context**
N/A

**Comment by manisfdcsfdx** [comment]
@reda-benhemmouche fix is available in beta. try sfdx plugins:install sfpowerkit@beta

**Comment by reda-benhemmouche** [comment]
Thank you for your support.

I install the beta and test again.
It seems that command sfdx sfpowerkit:project:manifest:diff is not working in the beta version !

```
$ sfdx sfpowerkit:project:manifest:diff -h
/Users/xxx/.local/share/sfdx/node_modules/sfpowerkit/lib/commands/sfpowerkit/project/manifest/diff.js:1
(function (exports, require, module, __filename, __dirname) { import { core, flags, SfdxCommand } from "@salesforce/command";
                                                                     ^
SyntaxError: Unexpected token {
    at NativeCompileCache._moduleCompile (~/.local/share/sfdx/client/7.57.1-dbf54fc584/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (~/.local/share/sfdx/client/7.57.1-dbf54fc584/node_modules/v8-compile-cache/v8-compile-cache.js:186:36)
    at Function._load (~/.local/share/sfdx/client/7.57.1-dbf54fc584/node_modules/@salesforce/lazy-require/lib/LazyLoader.js:89:24)
    at require (~/.local/share/sfdx/client/7.57.1-dbf54fc584/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
```
