### ISSUE TITLE
Error: Cannot find module '../../../../src/ui/progressBar'

### ISSUE THREAD

**Issue by mbathersby** [Accenture/sfpowerkit#282]
**Describe the bug**
Node error when trying to execute a profile diff

**To Reproduce**

Tried both: 
- sfdx sfpowerkit:org:profile:diff -p "Admin, Standard"
- sfdx sfpowerkit:org:profile:diff -p "System Administrator, Standard User"

_Error: Cannot find module '../../../../src/ui/progressBar'
    at Function._load (C:/Users/matt.bathersby/AppData/Local/sfdx/client/7.58.2-937f666ed4/node_modules/@salesforce/lazy-require/lib/LazyLoader.js:89:24)
    at require (C:/Users/matt.bathersby/AppData/Local/sfdx/client/7.58.2-937f666ed4/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (C:/Users/matt.bathersby/AppData/Local/sfdx/node_modules/sfpowerkit/lib/impl/source/profiles/profileDiff.js:38:23)
    at Module._compile (C:/Users/matt.bathersby/AppData/Local/sfdx/client/7.58.2-937f666ed4/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)_

**Comment by azlam-abdulsalam** [comment]
@mbathersby  while we debug this, can you switch to an older version? Also did you try a link vs sfdx plugins: install?

**Comment by mbathersby** [comment]
Thanks @azlam-abdulsalam. Happy to keep playing around with v1.45. Will let you now if I come across any other issues.

**Comment by azlam-abdulsalam** [comment]
We are able to reproduce it on windows.. working on the fix!

**Comment by manisfdcsfdx** [comment]
@mbathersby can you confirm other sfpowerkit commands are working for you .

**Comment by manisfdcsfdx** [comment]
@mbathersby hotfix applied can you test and confirm if the command works.
