### ISSUE TITLE
Profile reconcile command throwing errors when reconciling custom profile, NOT ABLE to reconcile profiles

### ISSUE THREAD

**Issue by WellWisherCoder** [Accenture/sfpowerkit#492]
`sfdx sfpowerkit:source:profile:reconcile -s  -n "Custom Profile"`

Error i got :

`WARNING: apiVersion configuration overridden at "51.0"
INFO     [2021-03-08 14:40:07.140 +0000] (sfpowerkit): Reconciling profile C:\Users\rp\Documents\VSCODE_PROJECTS\ORG\force-app\main\default\profi
ERROR    [2021-03-08 14:40:07.222 +0000] (sfpowerkit): Cannot read property 'getUnsupportedLicencePermissions' of undefined
    TypeError: Cannot read property 'getUnsupportedLicencePermissions' of undefined
        at ProfileReconcile.removeUnsupportedUserPermissions (C:\Users\rp\AppData\Local\sfdx\node_modules\sfpowerkit\lib\impl\source\profiles\profileReconcile.js:147:67)
        at ProfileReconcile.<anonymous> (C:\Users\rp\AppData\Local\sfdx\node_modules\sfpowerkit\lib\impl\source\profiles\profileReconcile.js:482:18)
        at Generator.next (<anonymous>)
        at C:\Users\rp\AppData\Local\sfdx\node_modules\sfpowerkit\lib\impl\source\profiles\profileReconcile.js:27:71
        at new Promise (<anonymous>)
        at __awaiter (C:\Users\rp\AppData\Local\sfdx\node_modules\sfpowerkit\lib\impl\source\profiles\profileReconcile.js:23:12)
        at ProfileReconcile.reconcileUserPermissions (C:\Users\rp\AppData\Local\sfdx\node_modules\sfpowerkit\lib\impl\source\profiles\profileReconcile.js:474:16)     
        at ProfileReconcile.<anonymous> (C:\Users\rp\AppData\Local\sfdx\node_modules\sfpowerkit\lib\impl\source\profiles\profileReconcile.js:533:24)
        at Generator.next (<anonymous>)
        at fulfilled (C:\Users\rp\AppData\Local\sfdx\node_modules\sfpowerkit\lib\impl\source\profiles\profileReconcile.js:24:58)
ERROR    [2021-03-08 14:40:07.227 +0000] (sfpowerkit): An error occured during profile reconcile. You can rerun the command after a moment.`

![image](https://user-images.githubusercontent.com/61293133/110336648-10576e80-804b-11eb-8e86-8b437f04ade6.png)

**Comment by azlam-abdulsalam** [comment]
@WellWisherCoder can you confirm the version number?

**Comment by manisfdcsfdx** [comment]
@WellWisherCoder hotfix is applied in v2.7.10
