### ISSUE TITLE
Error when running sfpowerkit:source:profile:retrieve

### ISSUE THREAD

**Issue by MarcDBehr** [Accenture/sfpowerkit#571]
Running on a Macbook (Big Sur 11.6) with sfdx (sfdx-cli/7.118.1 darwin-x64 node-v15.14.0) and trying to retrieve the profiles from a partial data sandbox, I just started getting this error:

```
$ sfdx sfpowerkit:source:profile:retrieve -u qa -f force-app/main/default/profiles/ --loglevel=debug --json
{
  "status": 1,
  "name": "TypeError",
  "message": "The \"path\" argument must be of type string or an instance of Buffer or URL. Received undefined",
  "exitCode": 1,
  "commandName": "Retrieve",
  "stack": "TypeError [ERR_INVALID_ARG_TYPE]: The \"path\" argument must be of type string or an instance of Buffer or URL. Received undefined\n    at Object.openSync (node:fs:497:10)\n    at Object.writeFileSync (node:fs:1535:35)\n    at ProfileWriter.writeProfile (/Users/marcdbehr/.local/share/sfdx/node_modules/sfpowerkit/lib/impl/metadata/writer/profileWriter.js:59:12)\n    at ProfileSync.<anonymous> (/Users/marcdbehr/.local/share/sfdx/node_modules/sfpowerkit/lib/impl/source/profiles/profileSync.js:112:39)\n    at Generator.next (<anonymous>)\n    at fulfilled (/Users/marcdbehr/.local/share/sfdx/node_modules/sfpowerkit/lib/impl/source/profiles/profileSync.js:24:58)\n    at processTicksAndRejections (node:internal/process/task_queues:94:5)\nOuter stack:\n    at Function.wrap (/Users/marcdbehr/.local/share/sfdx/node_modules/sfpowerkit/node_modules/@salesforce/command/node_modules/@salesforce/core/lib/sfdxError.js:151:27)\n    at Retrieve.catch (/Users/marcdbehr/.local/share/sfdx/node_modules/sfpowerkit/node_modules/@salesforce/command/lib/sfdxCommand.js:259:67)\n    at processTicksAndRejections (node:internal/process/task_queues:94:5)\n    at async Retrieve._run (/Users/marcdbehr/.local/share/sfdx/node_modules/sfpowerkit/node_modules/@salesforce/command/lib/sfdxCommand.js:97:13)\n    at async Config.runCommand (/usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/config/lib/config.js:173:24)\n    at async SfdxMain.run (/usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/command/lib/main.js:27:9)\n    at async SfdxMain._run (/usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/command/lib/command.js:43:20)\n    at async Object.run (/usr/local/lib/node_modules/sfdx-cli/dist/cli.js:162:47)",
  "warnings": []
}
```

Tried on 2 different Macbooks with the same results. The command shows that it got to 20/37 profiles and then it stops.

**Comment by azlam-abdulsalam** [comment]
@genoud  Can you look into this?

@MarcDBehr  Can you run this without json flag and loglevel trace and send us the logs

**Comment by MarcDBehr** [comment]
Did some more testing. Ran the same command against the same org and repository branch on a Linux system and got the same error. I then tried running the command without the -f option/parameter and it worked fine on both the Linux and Mac.

The files in the profile directory were:

```
$ ls -l force-app/main/default/profiles/
total 45856
-rw-r--r--  1 marcdbehr  staff  823251 Sep 21 07:03 Admin.profile-meta.xml
-rw-r--r--  1 marcdbehr  staff  822145 Sep 21 07:03 Analytics Cloud Integration User.profile-meta.xml
-rw-r--r--  1 marcdbehr  staff  822350 Sep 21 07:03 Analytics Cloud Security User.profile-meta.xml
-rw-r--r--  1 marcdbehr  staff  857126 Sep 21 07:03 Automation Profile.profile-meta.xml
-rw-r--r--  1 marcdbehr  staff  857849 Sep 21 07:03 Boise Service.profile-meta.xml
-rw-r--r--  1 marcdbehr  staff  857815 Sep 21 07:03 CargoSalesforceSupport Profile.profile-meta.xml
-rw-r--r--  1 marcdbehr  staff  822452 Sep 21 07:03 Chatter External User.profile-meta.xml
-rw-r--r--  1 marcdbehr  staff  822444 Sep 21 07:03 Chatter Free User.profile-meta.xml
-rw-r--r--  1 marcdbehr  staff  822449 Sep 21 07:03 Chatter Moderator User.profile-meta.xml
-rw-r--r--  1 marcdbehr  staff  822966 Sep 21 07:03 ContractManager.profile-meta.xml
-rw-r--r--  1 marcdbehr  staff  824472 Sep 21 07:04 Customer Community Login User.profile-meta.xml
-rw-r--r--  1 marcdbehr  staff  823866 Sep 21 07:04 Customer Community Plus Login User.profile-meta.xml
-rw-r--r--  1 marcdbehr  staff  822447 Sep 21 07:04 Guest License User.profile-meta.xml
-rw-r--r--  1 marcdbehr  staff  820894 Sep 21 07:04 Identity User.profile-meta.xml
-rw-r--r--  1 marcdbehr  staff  857185 Sep 21 07:04 Jupiter Service.profile-meta.xml
-rw-r--r--  1 marcdbehr  staff  822464 Sep 21 07:04 Limited Access User.profile-meta.xml
-rw-r--r--  1 marcdbehr  staff  856783 Sep 21 07:04 Live Agent Profile.profile-meta.xml
-rw-r--r--  1 marcdbehr  staff  857281 Sep 21 07:04 Marketing Profile - Canada.profile-meta.xml
-rw-r--r--  1 marcdbehr  staff  857191 Sep 21 07:04 Marketing Profile.profile-meta.xml
-rw-r--r--  1 marcdbehr  staff  822943 Sep 21 07:04 MarketingProfile.profile-meta.xml
-rw-r--r--  1 marcdbehr  staff  794628 Sep 21 07:05 Minimum Access - Salesforce.profile-meta.xml
-rw-r--r--  1 marcdbehr  staff  857295 Sep 21 07:05 Operations Profile.profile-meta.xml
-rw-r--r--  1 marcdbehr  staff  858430 Sep 21 07:05 Oversight Integration.profile-meta.xml
-rw-r--r--  1 marcdbehr  staff  857869 Sep 21 07:05 ProAct Customer Success.profile-meta.xml
-rw-r--r--  1 marcdbehr  staff  857894 Sep 21 07:05 ProAct Service.profile-meta.xml
-rw-r--r--  1 marcdbehr  staff  347362 Sep 20 16:03 Read Only - All Data API.profile-meta.xml
-rw-r--r--  1 marcdbehr  staff  186225 Sep 20 16:03 Read Only - Dashboards.profile-meta.xml
-rw-r--r--  1 marcdbehr  staff  188580 Sep 20 16:03 ReadOnly.profile-meta.xml
-rw-r--r--  1 marcdbehr  staff  171645 Sep 20 16:03 Sales Profile - AC.profile-meta.xml
-rw-r--r--  1 marcdbehr  staff  218960 Sep 20 16:03 Sales Profile - Canada.profile-meta.xml
-rw-r--r--  1 marcdbehr  staff  217525 Sep 20 16:03 Sales Profile - Cargo Canada.profile-meta.xml
-rw-r--r--  1 marcdbehr  staff  183596 Sep 20 16:03 Sales Profile - Cold Chain.profile-meta.xml
-rw-r--r--  1 marcdbehr  staff  202521 Sep 20 16:03 Sales Profile - InSinkErator.profile-meta.xml
-rw-r--r--  1 marcdbehr  staff  225024 Sep 20 16:03 Sales Profile.profile-meta.xml
-rw-r--r--  1 marcdbehr  staff  194616 Sep 20 16:03 SolutionManager.profile-meta.xml
-rw-r--r--  1 marcdbehr  staff  189756 Sep 20 16:03 Standard.profile-meta.xml
-rw-r--r--  1 marcdbehr  staff  155811 Sep 20 16:03 UnsubscribeEmail Profile.profile-meta.xml
```

**Comment by MarcDBehr** [comment]
Without the json and loglevel flags, I get

```$ sfdx sfpowerkit:source:profile:retrieve -u qa -f force-app/main/default/profiles/
INFO [2021-09-20 20:06:58.929 +0000] (sfpowerkit): Number of profiles found in the target org 37
Loading profiles in batches  - PROGRESS  | ██████████████████████░░░░░░░░░░░░░░░░░░ | 20/37  ProfilesERROR running sfpowerkit:source:profile:retrieve:  The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
```

**Comment by genoud** [comment]
Hi @MarcDBehr 

This is because you have in you folder a profile with the fullName tag in the content not matching the profile file name.

Thanks

**Comment by MarcDBehr** [comment]
Hi @genoud 

Interesting... not sure how we were able to download profiles like this, but it looks like we have 2 profiles that are missing the fullName tag completely. 

Would it be possible to add something into the code that when an issue occurs (like this) that the offending profile name be written out? Also, the process seems to hang when this occurs, so maybe it would also exit rather than hanging.

Thanks

**Comment by azlam-abdulsalam** [comment]
@MarcDBehr  Is these the profiles with "(" or any other characters in their names. I have seen an issue where SF started encoding the filenames but the api says otherwise

**Comment by MarcDBehr** [comment]
@azlam-abdulsalam It does not look like that was the issue. I found that there was one profile that I had locally that was not installed in the specified org that I ran the reconcile against. If I tried to reconcile with an org that had that profile, it worked fine.

The error message

**Comment by azlam-abdulsalam** [comment]
@genoud  lets handle this scenario, by reporting it in the end what we are not able to fetch. What so you think?

**Comment by genoud** [comment]
I pushed the fix. I was wrong. This was happening because some profiles in the folder does not exist in target org. So even if the fullName tag is missing or does not match the file name, the retrieve should work.

**Comment by genoud** [comment]
@MarcDBehr can you test the change?
